# syntax=docker/dockerfile:1

FROM golang:1.19

WORKDIR /api
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /features-api

EXPOSE 8083

CMD ["/features-api" ]